version: '3.8'

services:

  db:
    image: postgres:9.6.21
    environment:
      POSTGRES_DB: szamologep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 697ef061-b22a-4ea2-963f-3e39a1d1b008
    ports:
      - '25432:5432'
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: szamologep # :@version@ - haven't figured out how to add yet
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'